#!/bin/bash

apt-get update > /dev/null

echo Container Started
pivpnFilesDir="/usr/local/src/pivpn"
pivpnScriptDir="/opt/pivpn"

script(){
   ln -sf -T "${pivpnFilesDir}/scripts/${VPN}/bash-completion" /etc/bash_completion.d/pivpn
   ln -sf -T "${pivpnFilesDir}/scripts/${VPN}/pivpn.sh" /usr/local/bin/pivpn
   ln -sf "${pivpnFilesDir}/scripts/" "${pivpnScriptDir}"
}

if [ -f /etc/wireguard/wg0.conf ]
then
   echo "VPN Server exists"
   echo "If you have changed Variables in a running PIVPN Install run reconf"
   VPN=wireguard
   echo "Starting Wireguard"
   if ! [[ `dpkg -l | grep 'wireguard-tools\|qrencode'` ]]; then
   echo "deb http://deb.debian.org/debian buster-backports main non-free" >> /etc/apt/sources.list
   apt-get update && apt install -y --no-install-recommends wireguard-tools qrencode iproute2; fi
   # Symlink
   script
   # Generate Certificate
   echo "Generating Client Certificate."
   pivpn -a -n ${CLIENT_NAME:=pivpn} || true
   
   # IPTables Fix
   # sudo iptables -P FORWARD ACCEPT
   sudo iptables --table nat -A POSTROUTING -o "${INTERFACE:=eth0}" -j MASQUERADE
   # sudo iptables -t nat -C POSTROUTING -s "10.8.0.0/24" -o "eth0" -j MASQUERADE

   
   # systemctl enable wg-quick@wg0.service
   # systemctl start wg-quick@wg0.service
   # sleep 2
   wg-quick up wg0
   while :;do sleep 3; done
elif [ -f /etc/openvpn/server.conf ]
then
   echo "VPN Server exists"
   echo "If you have changed Variables in a running PIVPN Install run reconf"
   VPN=openvpn
   echo "Starting Openvpn"
   if ! [[ `dpkg -l | grep 'openvpn\|grepcidr\|expect\|gnupg'` ]]; then
   apt-get update && apt install -y --no-install-recommends gnupg openvpn grepcidr expect iproute2; fi
   # Symlink
   script
   # Generate Certificate
   echo "Generating Client Certificate."
   pivpn -a -n ${CLIENT_NAME} -p ${CLIENT_PASSWD:=nopass} -d 1080 || true
 
   # IPTables Fix
   #sudo iptables -P FORWARD ACCEPT
   sudo iptables --table nat -A POSTROUTING -o "${INTERFACE:=eth0}" -j MASQUERADE
 
   systemctl enable openvpn
   printf "\\n\\n::: PiVPN Service Started\\n"
   openvpn --config /etc/openvpn/server.conf --log /etc/openvpn/openvpn.log
else
   echo "VPN Server does not exist."
   echo "Pre Config of PIVPN."
   mkdir -p /etc/pivpn
   sudo -E bash setupVars
   INSTALLER=/etc/pivpn/install.sh
   mkdir -p /usr/local/src/pivpn/
   echo "deb http://deb.debian.org/debian buster-backports main non-free" >> /etc/apt/sources.list > /dev/null
   apt-get update && apt install -y --no-install-recommends wireguard-tools qrencode iproute2 > /dev/null
   # Variables are needed in the functions call later.
   useUpdateVars=true
   PLAT=Ubuntu
 
    curl -fsSL0 https://install.pivpn.io -o "${INSTALLER}" \
    && sed -i 's/debconf-apt-progress --//g' "${INSTALLER}" \
    && sed -i '/setStaticIPv4 #/d' "${INSTALLER}" \
    && sed -i 's/WIREGUARD_SUPPORT=0/WIREGUARD_SUPPORT=1/g' "${INSTALLER}" \
    && sed -i 's/PIVPN_DEPS+=(linux-headers-amd64 wireguard-dkms)/sleep 1/g' "${INSTALLER}" \
    && sed -i 's/PIVPN_DEPS+=(linux-headers-generic wireguard-dkms)/sleep 1/g' "${INSTALLER}" \
    && sed -i 's/sync/# sync/g' "${INSTALLER}" \
    && chmod +x "${INSTALLER}" \
    && bash "${INSTALLER}" --unattended /etc/pivpn/setupVars.conf --reconfigure
   
   echo CLIENT_NAME: "${CLIENT_NAME:=pivpn}"
   
   printf "\\n::: Installation Complete!\\n\\n"
   printf "\\n\\n::: PiVPN Service Started\\n"
   if [ -f /etc/wireguard/wg0.conf ]
   then
      VPN=wireguard
      script
      sudo iptables --table nat -A POSTROUTING -o "${INTERFACE:=eth0}" -j MASQUERADE
      wg-quick up wg0
      pivpn -a -n ${CLIENT_NAME:=pivpn} || true
      wg syncconf wg0 <(wg-quick strip wg0)
      while :;do sleep 3; done
   elif [ -f /etc/openvpn/server.conf ]
   then
      VPN=openvpn
      script
      systemctl enable openvpn
      pivpn -a -n ${CLIENT_NAME} -d 1080 || true
      openvpn --config /etc/openvpn/server.conf --log /etc/openvpn/openvpn.log
   fi
fi   
