name: PIVPN

on:
    workflow_dispatch:
    push:
      branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKER_USER }}"/pivpn-openvpn:latest-dev \
            --platform linux/arm64 .
#  linux/amd64,linux/arm64/v8,linux/arm/v5,linux/arm/v6 
# ,linux/386,linux/mips64le,linux/ppc64le,linux/s390x,linux/arm64/v8,linux/amd64,linux/arm/v5
