name: ci

on:
    workflow_dispatch:
    push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          opt: platform=linux/amd64,linux/arm64;linux/arm/v6
          tags: archef2000/pivpn-openvpn:latest-dev
          cache-from: type=registry,ref=archef2000/pivpn-openvpn:latest
          cache-to: type=inline
