name: Docker PIVPN

on:
    workflow_dispatch:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD   
    - name: docker buildx multiarch
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multiarch --driver docker-container --use
        docker buildx inspect --bootstrap
    - name: docker build docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |
        docker buildx build . -t $DOCKER_USER/pivpn-openvpn:latest_armv5 --platform linux/arm/v6 --push  
        docker buildx build . -t $DOCKER_USER/pivpn-openvpn:latest_amd64 --platform linux/amd64 --push
        docker buildx build . -t $DOCKER_USER/pivpn-openvpn:latest_armv6 --platform linux/arm/v5 --push
#        docker buildx build . -t $DOCKER_USER/pivpn-openvpn:latest_arm64 --platform linux/arm64 --push          
        
    - name: docker build docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |   
        docker manifest create \
        archef2000/pivpn-openvpn:latest-dev \
        --amend archef2000/pivpn-openvpn:latest-amd64 \
        --amend archef2000/pivpn-openvpn:latest-armv6 \
        --amend archef2000/pivpn-openvpn:latest-armv5

        docker manifest push archef2000/pivpn-openvpn:latest-dev
        
        
 #       --amend archef2000/pivpn-openvpn:latest-arm64        
        
        
        
        
        
        
#  linux/amd64,linux/arm64/v8,linux/arm/v5,linux/arm/v6 
# ,linux/386,linux/mips64le,linux/ppc64le,linux/s390x,linux/arm64/v8,linux/amd64,linux/arm/v5
