name: ci

on:
    workflow_dispatch:
    push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: actions/checkout@v2
        run: |
          docker buildx rm default
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name default --driver docker-container --use
          docker buildx inspect --bootstrap
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: archef2000/pivpn-openvpn:latest-dev
          cache-from: type=registry,ref=archef2000/pivpn-openvpn:latest
          cache-to: type=inline
