name: Docker SSLH 

on:
    workflow_dispatch:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker buildx multiarch
      run: |
        docker buildx create --name multiarch
        docker buildx use multiarch
        docker buildx inspect --bootstrap
        
    - name: docker build docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |
        docker buildx build . -f Dockerfile.amd64 -t $DOCKER_USER/pivpn-openvpn:latest --platform linux/amd64 --push
# ,linux/386,linux/mips64le,linux/ppc64le,linux/s390x,linux/arm64/v8,linux/amd64,linux/arm/v5
